# Railway Deployment Configuration
[build]
  builder = "NIXPACKS"

[deploy]
  startCommand = "npm start"
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 10

[variables]
  NODE_ENV = "production"
  # Core AI API Keys - Set in Railway dashboard
  OPENAI_API_KEY = ""
  STABILITY_AI_API_KEY = ""
  
  # Optional: Additional API Keys for enhanced features
  PEXELS_API_KEY = ""
  PIXABAY_API_KEY = ""
  UNSPLASH_ACCESS_KEY = ""
  YOUTUBE_API_KEY = ""
  NEWS_API_KEY = ""
  GIPHY_API_KEY = ""
