# Railway Deployment Configuration
[build]
  builder = "NIXPACKS"

[deploy]
  startCommand = "npm start"
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 10

[variables]
  NODE_ENV = "production"
  # Placeholder for OpenAI API key - will be set in Railway dashboard
  OPENAI_API_KEY = ""
